import {Component, OnInit, Output, EventEmitter }from '@angular/core'; 
@Component( {
selector:'app-input-button-unit', 
template:` 
<p> 
{{title}}
</p > 
<input #inputElementRef type="text" [value]= "todoValue" placeholder="write your todo here"
  (keyup.enter)="sendTodo($event.target.value)">
<button (click)="sendTodo(inputElementRef.value)">Save</button>

`, 
styleUrls:['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
    @Output() submitTodo: EventEmitter<string> = new EventEmitter();
    title: string;
    todoValue: string = "Enter your todo here";
    generateTitle(): string {
        return "this sentence was generated by a method";
    }
    setTitle(defaultTitle: string) {
        this.title = defaultTitle;
    }
    sendTodo(newTitle:string):void {
        this.submitTodo.emit(newTitle)
    }
    constructor() {

    }

    ngOnInit() {
        this.setTitle("This is my first Angular App Isn't that exciting?");
    }

}
