import {Component, OnInit }from '@angular/core'; 

@Component( {
selector:'app-input-button-unit', 
template:` 
<p> 
{{title}}
</p > 
<input #inputElementRef type="text" [value]= "todoValue" placeholder="write your todo here"
  (keyup.enter)="addTodo($event.target.value)">
<button (click)="addTodo(inputElementRef.value)">Save</button>
<ul>
<li *ngFor= "let todo of todoList">{{todo.title}}</li>
</ul>
`, 
styleUrls:['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
    title: string;
    todoValue: string = "Enter your todo here";
    todoList = []


    addTodo(newTodo: string):void {
        this.todoList.push({title:newTodo});
    }
    generateTitle(): string {
        return "this sentence was generated by a method";
    }
    setTitle(defaultTitle: string) {
        this.title = defaultTitle;
    }
    constructor() {

    }

    ngOnInit() {
        this.setTitle("This is my first Angular App Isn't that exciting?");
    }

}
