import {Component, OnInit }from '@angular/core'; 

@Component( {
selector:'app-input-button-unit', 
template:` 
<p> 
the titel is: {{title}}
</p > 
<input #inputElementRef type="text" [value]= todoValue 
  (keyup.enter)="addTodo($event.target.value)">
<button (click)="addTodo(inputElementRef.value)">Save</button>
<ul>
<li *ngFor= "let todo of todoList">{{todo}}</li>
</ul>
`, 
styleUrls:['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
title: string;
todoValue: string="Enter your todo here";
todoList=[]


 addTodo(newTodo: string){
  this.todoList.push(newTodo);
}
generateTitle():string {
return "this sentence was generated by a method";
}

constructor() {

}

ngOnInit() {
  this.changeTitle("This is my first Angular App boooooooooo");
}

}
